server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: mo-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://144.34.218.146:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    druid:
      #初始化时建立物理连接的个数
      initial-size: 5
      # 数据库连接池的最小维持连接数
      min-idle: 5
      #最大连接池数量 maxIdle已经不在使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 2000



eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/,http://server3:7003/eureka/
  instance:
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true


info:
  app.name: onemo-springcloud
  company.name: www.wdfu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$